swagger: "2.0"

info:
  title: "/"
  version: "1.0"

basePath: /v1.0

paths:
  /:
    post:
      summary: Generate message
      description: Generates a greeting message.
      operationId: new_flask_app.home
      produces:
        - text/plain;
      responses:
        200:
          description: greeting response
          schema:
            type: string
          examples:
            "text/plain": "Hello world"
  /books:
    post:
      summary: generates list of books
      description: Generates a 200 code and books from json file
      operationId: new_flask_app.books
      produces:
        - application/json;
      responses:
        200:
          description: https code response and json file
          schema:
            type: object
          examples:
            "books": [{ "title": "xxx","author": "yyy","timestamp": "YYYY-MM-DD HH:MM:SS" }]