openapi: 3.0.0

info:
  title: "/"
  version: "1.0"


servers:
  - url: "/v1.0"

components:
  schemas:
    Book:
      type: object
      required:
        - author
        - title
      properties:
        author:
          type: string
        title:
          type: string

paths:
  /home:
    get:
      summary: Generate message
      description: Generates a greeting message.
      operationId: new_flask_app.home
      #      produces:
      #        - text/plain
      responses:
        200:
          description: greeting response
          #          schema:
          #            type: string
          #          examples:
          #            "Hello world"
  /books:
    get:
      summary: generates list of books
      description: Generates a 200 code and books from json file
      operationId: new_flask_app.books_get
      #      produces:
      #        - application/json;
      responses:
        200:
          description: https code response and json file
          #          schema:
          #            type: object
          #          examples:
          #            "books": [{ "title": "xxx","author": "yyy","timestamp": "YYYY-MM-DD HH:MM:SS" }]
    post:
      summary: enables to add books
      description: adds books by its title and author
      operationId: new_flask_app.books_post
      #      produces:
      #        - application/json
      requestBody:
        description: "Book to add"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "book"
              $ref: "#/components/schemas/Book"
      responses:
        200:
          description: https code response and json file
  /books/{id}:
    get:
      summary: Get book by ID
      operationId: new_flask_app.books_id_get
      parameters:
        - name: id
          in: path
          description: ID of the book
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '404':
          description: Book not found
    put:
      operationId: new_flask_app.books_id_put
      requestBody:
        description: "Book to modify"
        required: True
        content:
          application/json:
            schema:
              x-body-name: "data"
              $ref: "#/components/schemas/Book"
      parameters:
        - name: id
          in: path
          description: ID of the book
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                x-body-name: "data"
                $ref: '#/components/schemas/Book'
        '404':
          description: Book not found
    delete:
      operationId: new_flask_app.books_id_delete
      parameters:
        - name: id
          in: path
          description: ID of the book to be deleted
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Book deleted successfully
        '404':
          description: Book not found
  /authors:
    get:
      summary: generates list of authors
      description: Generates a 200 code and list of authors as json file
      operationId: new_flask_app.authors
      #      produces:
      #        - application/json;
      responses:
        200:
          description: https code response and json file