name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up to Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Google Container Registry
      uses: docker/login-action@v1
      with:
        registry: gcr.io
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}

    - name: Lowercase repo name
      id: repo_lower
      run: echo "REPO_LOWER=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.ref == 'refs/heads/master' }}
        tags: gcr.io/${{ secrets.GCP_PROJECT_NAME }}/${{ env.REPO_LOWER }}:${{ github.sha }}
        
    - name: Output container image URL
      run: echo ${{ steps.docker_build.outputs.digest }}
        
